name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f24268df9bdd72d499f8b69fe754303057e6617782f415251ed54ebb5f49b0c8"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
