name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bf7bf2cc5c8b4b47772a94e5921771442140d7d5facb523af8da6e0e57f4d7c"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
